// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SciFiPortfolio.Data.Context;

#nullable disable

namespace SciFiPortfolio.Data.Migrations
{
    [DbContext(typeof(SciFiContext))]
    [Migration("20260809095116_AddVisitorEntity")]
    partial class AddVisitorEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectCardEntityTagEntity", b =>
                {
                    b.Property<string>("CardsId")
                        .HasColumnType("text");

                    b.Property<string>("TagsId")
                        .HasColumnType("text");

                    b.HasKey("CardsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProjectCardEntityTagEntity");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.PageContentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("PageContents");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.PageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentPageId")
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.ProjectCardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ImageAltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectCards");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.TagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.VisitorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("ProjectCardEntityTagEntity", b =>
                {
                    b.HasOne("SciFiPortfolio.Entities.ProjectCardEntity", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SciFiPortfolio.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.PageContentEntity", b =>
                {
                    b.HasOne("SciFiPortfolio.Entities.PageEntity", "Page")
                        .WithOne("PageContent")
                        .HasForeignKey("SciFiPortfolio.Entities.PageContentEntity", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.PageEntity", b =>
                {
                    b.HasOne("SciFiPortfolio.Entities.PageEntity", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.ProjectCardEntity", b =>
                {
                    b.OwnsOne("SciFiPortfolio.Models.AppLink", "AppLink", b1 =>
                        {
                            b1.Property<string>("ProjectCardEntityId")
                                .HasColumnType("text");

                            b1.Property<string>("IconName")
                                .HasColumnType("text");

                            b1.Property<string>("LinkText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LinkUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PageId")
                                .HasColumnType("text");

                            b1.Property<string>("PageSlug")
                                .HasColumnType("text");

                            b1.HasKey("ProjectCardEntityId");

                            b1.ToTable("ProjectCards");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCardEntityId");
                        });

                    b.OwnsOne("SciFiPortfolio.Models.HyperLink", "Hyperlink", b1 =>
                        {
                            b1.Property<string>("ProjectCardEntityId")
                                .HasColumnType("text");

                            b1.Property<string>("IconName")
                                .HasColumnType("text");

                            b1.Property<string>("LinkText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LinkUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectCardEntityId");

                            b1.ToTable("ProjectCards");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCardEntityId");
                        });

                    b.Navigation("AppLink")
                        .IsRequired();

                    b.Navigation("Hyperlink")
                        .IsRequired();
                });

            modelBuilder.Entity("SciFiPortfolio.Entities.PageEntity", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("PageContent");
                });
#pragma warning restore 612, 618
        }
    }
}
